### ISSUE TITLE
9999 should be valid microwave time. 

### ISSUE THREAD

**Issue by ThrowsException** [D-L-M/get-microwave-time#2]
99:99 is a valid microwave time on a 4 digit display.

**Comment by ThrowsException** [comment]
Actually misread what the library was doing. its limiting to 5999 which would be 99:59 but microwaves can have 99:99 as a valid valid. The threshold should be 6039

**Comment by D-L-M** [comment]
Cannot reproduce: my microwave wraps the 60th second to the next minute
